

```
# This is formatted as code
```

class-A class is like a blueprint or template to create objects.

objects-instance of class

eg
class is WEATHER
OBJECTS WILL BE RAINY,SUNNY,COLD

Each object needs a way to talk about itself — that’s what self does!
It is like saying “me” inside the class.

In [ ]:
class Fruit:
 def show(self):
  print("Fruits are healthy")
apple=Fruit()
banana=Fruit()
apple.show()

Fruits are healthy


class is the keyword to define the class
to create an object====> object=class name()


**Q1)PROGRAM FOR STUDENTS AS CLASS**

In [ ]:
class Car:
    def honk(self):
        print("Beep! Beep!")

c1 = Car()
c2 = Car()
c1.honk()
c2.honk()

Beep! Beep!
Beep! Beep!


In [ ]:
class Calculator:
  def add(self,a,b):
       print("Sum:", a + b)
  def multiply(self,a, b):
       print("Product:", a * b)
calc =Calculator()
calc.add(5,3)
calc.multiply(4,8)

Sum: 8
Product: 32


In [ ]:
class Student:
    def set_name(self, name):
        self.name = name

    def show(self):
        print("Name:", self.name)

s1 = Student()
s1.set_name("HELLO_WORLD")
s1.show()

Name: HELLO_WORLD


In [ ]:
class Student:
    def set_data(self, name, age):
        self.name = name
        self.age = age
    def show_data(self):
        print("Name:", self.name)
        print("Age:", self.age)
s1 = Student()
s1.set_data("Mahendra", 20)
s1.show_data()

Name: Mahendra
Age: 20


In [ ]:
class Rectangle:
    def set_values(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimtr(self):
        return 2 * (self.length + self.width)
o1 = Rectangle()
o1.set_values(7, 3)
print("Area:", o1.area())
print("Perimeter:", o1.perimtr())

Area: 21
Perimeter: 20


In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"Hello, {self.name}! Welcome to Rajkot city !")
p1 = Person("Mahendra")
p1.greet()

Hello, Mahendra! Welcome to Rajkot city !


In [ ]:
class Bird:
    def __init__(self, name, age, city):
        self.name = name
        self.age = age
        self.city = city
    def chirp(self):
        print(f"{self.name} is chirping. Age: {self.age} and the city is {self.city}")
b1 = Bird("dove", 2, "Mumbai")
b2 = Bird("hummingbird", 4, "Delhi")
b1.chirp()
b2.chirp()


dove is chirping. Age: 2 and the city is Mumbai
hummingbird is chirping. Age: 4 and the city is Delhi


In [ ]:
class Circle:
    def set_radius(self, radius):
        self.radius = radius
        self.pi = 3.14

    def area(self):
        return self.pi * self.radius**2

    def diameter(self):
        return 2 * self.radius

    def circumference(self):
        return 2 * self.pi * self.radius

c1 = Circle()
c1.set_radius(6)
print("Area:", c1.area())
print("Diameter:", c1.diameter())
print("Circumference:", c1.circumference())

Area: 113.04
Diameter: 12
Circumference: 37.68


In [ ]:
a = [1,2,3]
b = [4,5,6]
result =[]
for i in range(len(a)):
    pass # Placeholder for further loop logic


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = 2
print(a*b)

[2 4 6]


In [ ]:
import numpy as np
b = np.ones((4,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
c = np.arange(1,17,2)
print(c)

[ 1  3  5  7  9 11 13 15]


In [ ]:
import numpy as np
arr1=np.array([10,20,30])

In [ ]:
import numpy as np
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
f=np.random.rand(2,5)
print(f)

[[0.65610879 0.87212087 0.58740825 0.24300475 0.61344134]
 [0.00263505 0.29262337 0.39528594 0.3283918  0.81983236]]


In [ ]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.T)

21
3.5
6
1
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([1,5,3])
arr2 = np.array([4,5,6])
print(arr + arr2)
print(arr * 2)
print(arr **2)

In [ ]:
import numpy as np
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
